### ISSUE TITLE
Webhook as env variable ?

### ISSUE THREAD

**Issue by abouchama** [ouadie-lahdioui/ipaas-devoxxMa-2018-alexa-skill#2]
Let's declare webhook as env var , that would be simple for the demo ? ;-)

`const WEBHOOK = "https://i-webhooktodbpsql-proj350166.6a63.fuse-ignite.openshiftapps.com/webhook/iasaqOSXL9Q0YNZm6eJqO8L2Tx2ucsTlm4HKJ7DGsRkqLB2cip";`

**Comment by ouadie-lahdioui** [comment]
Done.

The env var iss WEBHOOK.
